### ISSUE TITLE
Deploy running instance of Mauro and Orchestrator in TEST environment

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper-NHSD/nhsd-datadictionary-docker#11]
# Overview

Get the Mauro and Orchestrator tools running successfully on the NHSE TEST virtual machine.

# Tasks

- [x] Install necessary tools for environment setup on VM
- [x] Install Docker
- [x] Clone this repo on the VM
- [x] Build and run the containers on the VM
- [x] Configure correct networking of ports to access Mauro and the Orchestrator
- [x] Add user accounts to Mauro
- [x] Ingest the May 2024 data dictionary
- [x] Create a new `main` branch

# Related

- #4
